### ISSUE TITLE
client.py needs to be modified for python3

### ISSUE THREAD

**Issue by Lordling** [Shapeways/python-shapeways#2]
As in the title, we need to make use of the Shapeways Python API in our Python3 app, but the API seems to only be configured for Python2. The import of shapeways.client was failing until I made the following changes outlined in the image:

![screenshot from 2018-07-10 17-10-55](https://user-images.githubusercontent.com/6563220/42508775-5961f9b6-8467-11e8-81c7-40be40a873ea.png)

Currently the import and the construction of the client object seems to be fine after I made these changes, but I am still working and testing.

Would it be possible to get something like the configuration mentioned [here](https://techoverflow.net/2015/02/08/fixing-importerror-cannot-import-name-urlencode-in-python3/) into the official repo so that it's Python3-compatible? Currently the changes to the clients.py module are external to our application, and untracked ... and we would prefer official support.

**Comment by mboylevt** [comment]
Hi @Lordling,
Thanks for reporting, and apologies for the delay in reply.  I've gone ahead and updated the client with support for both python2 and python3: I'd appreciate it if you could give it a look and let me know if it's working for you.

In addition to making your requested change, I've also released a python2 and python3 compliant Oauth2 client, which you'll find in a parallel directory.  If you're interested, feel free to give that a try as well!  I'll leave this issue open until you're able to confirm the fix.

-matt

**Comment by mboylevt** [comment]
Going to close this out as resolved: if you have further issues please comment here.
